//(If exists) Possibly contains local data/mock data or IndexedDB utils.
const vehicles = [
    {
        id: 1,
        firstname: "John",
        lastname: "Doe",
        email: "john.doe@example.com",
        manufacturer: "Toyota",
        model: "Corolla",
        VIN: "1HGCM82633A123456",
        age: 5,
        manufacturedDate: "2018-01-01",
    },
    {
        id: 2,
        firstname: "Jane",
        lastname: "Smith",
        email: "jane.smith@example.com",
        manufacturer: "Honda",
        model: "Civic",
        VIN: "2HGCM82633A234567",
        age: 5,
        manufacturedDate: "2012-01-01",
    },
    {
        id: 3,
        firstname: "Michael",
        lastname: "Johnson",
        email: "michael.johnson@example.com",
        manufacturer: "Ford",
        model: "Focus",
        VIN: "3HGCM82633A345678",
        age: 5,
        manufacturedDate: "2011-01-01",
    },
    {
        id: 4,
        firstname: "Emily",
        lastname: "Davis",
        email: "emily.davis@example.com",
        manufacturer: "Chevrolet",
        model: "Malibu",
        VIN: "4HGCM82633A456789",
        age: 5,
        manufacturedDate: "2010-01-01",
    },
    {
        id: 5,
        firstname: "Chris",
        lastname: "Brown",
        email: "chris.brown@example.com",
        manufacturer: "Nissan",
        model: "Altima",
        VIN: "5HGCM82633A567890",
        age: 5,
        manufacturedDate: "2019-01-01",
    },
    {
        id: 6,
        firstname: "Sarah",
        lastname: "Wilson",
        email: "sarah.wilson@example.com",
        manufacturer: "Hyundai",
        model: "Elantra",
        VIN: "6HGCM82633A678901",
        age: 5,
        manufacturedDate: "2015-01-01",
    },
    {
        id: 7,
        firstname: "David",
        lastname: "Martinez",
        email: "david.martinez@example.com",
        manufacturer: "Kia",
        model: "Soul",
        VIN: "7HGCM82633A789012",
        age: 5,
        manufacturedDate: "2008-01-01",
    },
    {
        id: 8,
        firstname: "Sophia",
        lastname: "Garcia",
        email: "sophia.garcia@example.com",
        manufacturer: "Volkswagen",
        model: "Jetta",
        VIN: "8HGCM82633A890123",
        age: 5,
        manufacturedDate: "2012-01-01",
    },
    {
        id: 9,
        firstname: "James",
        lastname: "Anderson",
        email: "james.anderson@example.com",
        manufacturer: "Subaru",
        model: "Outback",
        VIN: "9HGCM82633A901234",
        age: 5,
        manufacturedDate: "2014-01-01",
    }
]

export default vehicles; 